"""add_email_verification_and_oauth_fields

Revision ID: ce8816044df8
Revises: b0561b798779
Create Date: 2026-01-18 21:14:49.139719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8816044df8'
down_revision: Union[str, Sequence[str], None] = 'b0561b798779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', name='otp_purpose', create_constraint=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    
    # Add is_email_verified as nullable first
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    # Set existing users as verified (grandfathered in)
    op.execute("UPDATE users SET is_email_verified = TRUE WHERE is_email_verified IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'is_email_verified', nullable=False)
    
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # Set verified_at for existing users
    op.execute("UPDATE users SET email_verified_at = created_at WHERE is_email_verified = TRUE AND email_verified_at IS NULL")
    
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    
    # Add auth_provider as nullable first
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=True))
    # Set existing users to email provider
    op.execute("UPDATE users SET auth_provider = 'email' WHERE auth_provider IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'auth_provider', nullable=False)
    
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'is_email_verified')
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
